import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { createProviderRegistry } from "../providers/index.js";
const env=(v,{strict=false}={})=>typeof v==="string"?v.replace(/\$\{([A-Z0-9_]+)\}/g,(_,k)=>{if(process.env[k]===undefined){if(strict)throw new Error(`缺少环境变量: ${k}`);return "";}return process.env[k];}):v;
export function validateStudioConfig(raw){const errors=[];if(!raw||typeof raw!=="object")errors.push("配置必须是对象");if(!Array.isArray(raw?.agents)||raw.agents.length===0)errors.push("至少需要一个 agents");const ids=new Set();for(const a of raw?.agents||[]){if(!a.id)errors.push("Agent 缺少 id");else if(ids.has(a.id))errors.push(`Agent id 重复: ${a.id}`);else ids.add(a.id);if(!a.role)errors.push(`Agent ${a.id||"?"} 缺少 role`);if(a.provider&&typeof a.provider!=="string")errors.push(`Agent ${a.id||"?"} provider 无效`);if(a.capabilities&&!Array.isArray(a.capabilities))errors.push(`Agent ${a.id||"?"} capabilities 必须是数组`);if(a.delegatesTo&&!Array.isArray(a.delegatesTo))errors.push(`Agent ${a.id||"?"} delegatesTo 必须是数组`);}if(!raw?.providers||typeof raw.providers!=="object")errors.push("缺少 providers");return {ok:errors.length===0,errors};}
export function loadStudioConfig(file){const path=resolve(file);if(!existsSync(path))throw new Error(`Studio 配置不存在: ${path}`);let raw;try{raw=JSON.parse(readFileSync(path,"utf8"));}catch(e){throw new Error(`Studio 配置 JSON 无效: ${e.message}`);}const check=validateStudioConfig(raw);if(!check.ok)throw new Error(`Studio 配置无效: ${check.errors.join("；")}`);const providers={};for(const [name,cfg] of Object.entries(raw.providers||{})){providers[name]={...cfg,apiKey:env(cfg.apiKey,{strict:process.env.STUDIO_STRICT_CONFIG==="1"}),baseURL:env(cfg.baseURL,{strict:process.env.STUDIO_STRICT_CONFIG==="1"})};}const defaultProvider=Object.keys(providers)[0];if(!defaultProvider)throw new Error("至少需要一个 Provider");const agents=raw.agents.map(a=>({...a,provider:a.provider||defaultProvider,prompt:a.prompt||`你是${a.role}。`}));const registry=createProviderRegistry(providers);return {...raw,agents:agents.map(a=>({...a,providerInstance:registry.get(a.provider)})),providers,registry};}
export function agentMap(config){return Object.fromEntries(config.agents.map(a=>[a.id,a]));}
export function createStudioProviders(config){return config.registry;}
export function publicStudioConfig(config){return {...config,providers:Object.fromEntries(Object.entries(config.providers||{}).map(([k,v])=>[k,{...v,apiKey:v.apiKey?"[redacted]":""}]))};}
export function layerAgent(config,layer){const preferred={requirements:["manager","planner"],engineering:["planner","technical-designer","developer"],development:["developer","technical-designer"],qa:["qa","reviewer"]}[layer]||[layer];return config.agents.find(a=>preferred.includes(a.id)||preferred.includes(a.role))||config.agents[0];}
