import { mkdirSync, readdirSync, readFileSync, writeFileSync, statSync, appendFileSync } from "node:fs";
import { join, resolve, relative } from "node:path";
import { randomUUID } from "node:crypto";
export const STUDIO_LAYERS=["requirements","engineering","development","qa"];
const templates={requirements:["requirements.md","feature-list.md","asset-spec.md","acceptance.md"],engineering:["quantified-spec.md","architecture.md","task-breakdown.md","test-plan.md"],development:["implementation-plan.md","change-list.md","risk-register.md"],qa:["qa-report.md","bug-list.md","performance-security.md"]};
function files(root,limit=200){const out=[];function walk(dir){for(const name of readdirSync(dir)){if([".git","node_modules",".cowork"].includes(name))continue;const p=join(dir,name);const s=statSync(p);if(s.isDirectory())walk(p);else if(out.length<limit)out.push(relative(root,p));}}walk(root);return out;}
function context(input,mode){const p=resolve(input);if(mode==="requirements"&&!statSync(p,{throwIfNoEntry:false}))return {input,mode,kind:"idea",files:[],text:String(input)};const isDir=statSync(p).isDirectory();return {input:p,mode,kind:isDir?"directory":"file",files:isDir?files(p):[],text:isDir?"":readFileSync(p,"utf8").slice(0,30000)};}
function fallback(mode,ctx,file){return "# "+file.replace(/[-_]/g," ")+"\n\nLayer: "+mode+"\nInput: "+ctx.input+"\n\n## Working Notes\n\n- Inspect the input and record evidence.\n- Keep scope explicit and identify open questions.\n- Produce reviewable, testable handoff content.\n"+(ctx.files.length?"\nFiles inspected: "+ctx.files.length+"\n":"");}
function prompt(mode,ctx,file){return "You are the "+mode+" layer of Studio CoWork. Produce the requested handoff document: "+file+". Input kind: "+ctx.kind+". Input path or idea: "+ctx.input+". Files: "+ctx.files.join(", ")+".\n\nInput content:\n"+ctx.text+"\n\nRules: be concrete, distinguish facts from assumptions, include acceptance/evidence, and do not claim code was changed. Return Markdown only.";}
export async function runStudioLayer({mode,input,output,provider=null,system="You are a careful Studio CoWork specialist.",logPath=null}){if(!STUDIO_LAYERS.includes(mode))throw new Error(`未知 Studio layer: ${mode}`);if(!input)throw new Error("独立层需要 input");const ctx=context(input,mode);const out=resolve(output||join(process.cwd(),`.studio-${mode}-${Date.now()}`));mkdirSync(out,{recursive:true});const log=(event)=>{if(logPath)appendFileSync(resolve(logPath),JSON.stringify({ts:new Date().toISOString(),...event})+"\n");};log({event:"layer.started",mode,input:ctx.input,provider:provider?.name||"offline"});const produced=[];for(const file of templates[mode]){try{let text;if(provider){const result=await provider.generate({role:mode,model:provider.model,system,user:prompt(mode,ctx,file)});text=typeof result==="string"?result:JSON.stringify(result,null,2);}else text=fallback(mode,ctx,file);writeFileSync(join(out,file),text.endsWith("\n")?text:text+"\n");produced.push(file);log({event:"document.written",file});}catch(error){log({event:"document.failed",file,error:error.message});throw error;}}const manifest={id:randomUUID(),layer:mode,input:ctx.input,output:out,provider:provider?.name||"offline",createdAt:new Date().toISOString(),files:produced,logPath:logPath?resolve(logPath):null};writeFileSync(join(out,"layer-manifest.json"),JSON.stringify(manifest,null,2)+"\n");log({event:"layer.completed",files:produced.length,manifest:join(out,"layer-manifest.json")});return manifest;}
