import { randomUUID } from "node:crypto";
const TASK_STATES=["pending","ready","running","submitted","approved","needs_revision","failed","cancelled"];
const ALLOWED={pending:["ready","cancelled"],ready:["running","cancelled"],running:["submitted","failed","cancelled"],submitted:["approved","needs_revision","failed","cancelled"],approved:[],needs_revision:["ready","failed","cancelled"],failed:["ready","cancelled"],cancelled:[]};
export class StudioTaskStore {
  constructor({db,eventLog}){this.db=db;this.events=eventLog;}
  create({versionId,stageKey,name,agentRole,taskType="document",format="md",outputName=name,acceptance=[],maxAttempts=3,idempotencyKey=null}){if(idempotencyKey){const existing=this.db.prepare("SELECT * FROM studio_tasks WHERE idempotency_key=?").get(idempotencyKey);if(existing)return this.get(existing.id);}const id=randomUUID();const ts=new Date().toISOString();this.db.prepare("INSERT INTO studio_tasks(id,version_id,stage_key,name,agent_role,task_type,status,format,output_name,acceptance,attempt,max_attempts,idempotency_key,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,versionId,stageKey,name,agentRole,taskType,"pending",format,outputName,JSON.stringify(acceptance),0,maxAttempts,idempotencyKey,ts,ts);this.events?.append("studio.task.created",{taskId:id,versionId,stageKey,name,idempotencyKey});return this.get(id);}
  get(id){const t=this.db.prepare("SELECT * FROM studio_tasks WHERE id=?").get(id);if(!t)throw new Error("未知 Studio 任务");return {...t,versionId:t.version_id,stageKey:t.stage_key,agentRole:t.agent_role,taskType:t.task_type,outputName:t.output_name,acceptance:JSON.parse(t.acceptance||"[]")};}
  list(versionId){return this.db.prepare("SELECT * FROM studio_tasks WHERE version_id=? ORDER BY created_at").all(versionId).map(t=>({...t,versionId:t.version_id,stageKey:t.stage_key,agentRole:t.agent_role,taskType:t.task_type,outputName:t.output_name,acceptance:JSON.parse(t.acceptance||"[]")}));}
  addDependency({taskId,dependsOnTaskId}){if(taskId===dependsOnTaskId)throw new Error("任务不能依赖自身");const a=this.db.prepare("SELECT id,version_id FROM studio_tasks WHERE id=?").get(taskId);const b=this.db.prepare("SELECT id,version_id FROM studio_tasks WHERE id=?").get(dependsOnTaskId);if(!a||!b)throw new Error("任务依赖目标不存在");if(a.version_id!==b.version_id)throw new Error("任务依赖不能跨版本");const seen=new Set([dependsOnTaskId]);const stack=[dependsOnTaskId];while(stack.length){const id=stack.pop();for(const row of this.db.prepare("SELECT depends_on_task_id FROM studio_task_dependencies WHERE task_id=?").all(id)){if(row.depends_on_task_id===taskId)throw new Error("任务依赖会形成环路");if(!seen.has(row.depends_on_task_id)){seen.add(row.depends_on_task_id);stack.push(row.depends_on_task_id);}}}this.db.prepare("INSERT INTO studio_task_dependencies(task_id,depends_on_task_id) VALUES(?,?)").run(taskId,dependsOnTaskId);this.events?.append("studio.task.dependency.added",{taskId,dependsOnTaskId});}
  dependenciesDone(id){return this.db.prepare("SELECT COUNT(*) AS n FROM studio_task_dependencies d JOIN studio_tasks t ON t.id=d.depends_on_task_id WHERE d.task_id=? AND t.status<>'approved'").get(id).n===0;}
  ready(versionId,stageKey=null){return this.list(versionId).filter(t=>(!stageKey||t.stageKey===stageKey)&&(t.status==="pending"||t.status==="failed"||t.status==="needs_revision")&&this.dependenciesDone(t.id)&&t.attempt<t.max_attempts);}
  claim(id,{workerId=randomUUID(),leaseMs=120000}={}){const now=new Date();const leaseId=randomUUID();const until=new Date(now.getTime()+leaseMs).toISOString();const result=this.db.prepare("UPDATE studio_tasks SET status='running',attempt=attempt+1,lease_id=?,worker_id=?,claimed_at=?,heartbeat_at=?,lease_expires_at=?,updated_at=? WHERE id=? AND status='ready' AND attempt<max_attempts").run(leaseId,workerId,now.toISOString(),now.toISOString(),until,now.toISOString(),id);if(!result.changes)throw new Error("任务无法 claim，可能已被其他 Worker 占用");this.events?.append("studio.task.claimed",{taskId:id,workerId,leaseId});return {...this.get(id),leaseId,workerId};}
  heartbeat(id,leaseId,{leaseMs=120000}={}){const until=new Date(Date.now()+leaseMs).toISOString();const result=this.db.prepare("UPDATE studio_tasks SET heartbeat_at=?,lease_expires_at=?,updated_at=? WHERE id=? AND status='running' AND lease_id=?").run(new Date().toISOString(),until,new Date().toISOString(),id,leaseId);if(!result.changes)throw new Error("任务租约无效或已过期");return this.get(id);}
  recoverRunning({now=new Date(),maxAgeMs=0}={}){const rows=this.db.prepare("SELECT * FROM studio_tasks WHERE status='running'").all();const recovered=[];for(const t of rows){const expired=t.lease_expires_at?Date.parse(t.lease_expires_at)<=now.getTime():maxAgeMs>0&&now.getTime()-Date.parse(t.updated_at)>=maxAgeMs;if(expired){this.db.prepare("UPDATE studio_tasks SET status='failed',updated_at=?,lease_id=NULL,worker_id=NULL WHERE id=? AND status='running' AND lease_expires_at=?").run(now.toISOString(),t.id,t.lease_expires_at);this.events?.append("studio.task.recovered",{taskId:t.id,from:"running",to:"failed"});recovered.push(this.get(t.id));}}return recovered;}
  retry(id){const t=this.get(id);if(!["failed","needs_revision"].includes(t.status))throw new Error("当前任务不可重试");if(t.attempt>=t.max_attempts)throw new Error("任务已达到最大重试次数");return this.transition(id,"ready",{retry:true});}
  transition(id,to,meta={}){const t=this.get(id);if(!TASK_STATES.includes(to)||!ALLOWED[t.status]?.includes(to))throw new Error(`非法 Studio 任务迁移: ${t.status} -> ${to}`);const ts=new Date().toISOString();const attempt=to==="running"?t.attempt+1:t.attempt;this.db.prepare("UPDATE studio_tasks SET status=?,attempt=?,updated_at=?,lease_id=NULL,worker_id=NULL WHERE id=?").run(to,attempt,ts,id);this.events?.append("studio.task."+to,{taskId:id,attempt,...meta});return this.get(id);}
}