import { mkdirSync, writeFileSync, cpSync, chmodSync, readdirSync, statSync, readFileSync, renameSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { randomUUID, createHash } from "node:crypto";
import { buildManifest, writeManifest } from "./manifest.js";
import { StudioArtifactStore } from "./artifacts.js";
const VERSION_RE=/^\d+\.\d+\.\d+\.\d+$/;
const STAGES=["planning","design","asset-spec","production","playable"];
const now=()=>new Date().toISOString();
const sha256=data=>createHash("sha256").update(data).digest("hex");
function filesOf(root,relative=""){const dir=join(root,relative);const out=[];for(const name of readdirSync(dir)){const rel=join(relative,name);const full=join(root,rel);const st=statSync(full);if(st.isDirectory())out.push(...filesOf(root,rel));else out.push({path:rel.replaceAll("\\","/"),size:st.size,checksum:sha256(readFileSync(full))});}return out;}
function copyTree(source,target){mkdirSync(target,{recursive:true});cpSync(source,target,{recursive:true,force:true});}
export class StudioVersionStore {
  constructor({db,eventLog,projectRoot}){this.db=db;this.events=eventLog;this.root=resolve(projectRoot);}
  createProject({id=randomUUID(),name}){const ts=now();this.db.prepare("INSERT INTO projects(id,name,root_path,created_at) VALUES(?,?,?,?)").run(id,name,this.root,ts);this.events?.append("project.created",{projectId:id,name});return {id,name};}
  createVersion({projectId,version,baseVersionId=null}){if(!VERSION_RE.test(version))throw new Error("版本必须是 major.minor.patch.build 四段格式");const p=this.db.prepare("SELECT * FROM projects WHERE id=?").get(projectId);if(!p)throw new Error("未知项目");if(baseVersionId&&!this.db.prepare("SELECT id FROM versions WHERE id=? AND project_id=?").get(baseVersionId,projectId))throw new Error("基线版本不存在");const id=randomUUID();const workspace=join(p.root_path,"workspaces",version);if(existsSync(workspace))throw new Error("workspace 已存在，拒绝覆盖");mkdirSync(workspace,{recursive:true});for(const d of ["documents","source","assets","tests","build"])mkdirSync(join(workspace,d));this.db.prepare("INSERT INTO versions(id,project_id,version,status,base_version_id,workspace_path) VALUES(?,?,?,?,?,?)").run(id,projectId,version,"planning",baseVersionId,workspace);for(const stage of STAGES)this.db.prepare("INSERT INTO stages(id,version_id,stage_key,status) VALUES(?,?,?,?)").run(randomUUID(),id,stage,"pending");this.events?.append("version.created",{versionId:id,version,workspace,baseVersionId});return this.get(id);}
  get(id){const v=this.db.prepare("SELECT * FROM versions WHERE id=?").get(id);if(!v)throw new Error("未知版本");return v;}
  approve(id){const v=this.get(id);if(v.status!=="planning")throw new Error("只有 planning 版本可以 approve");const stages=this.db.prepare("SELECT status FROM stages WHERE version_id=?").all(id);if(stages.some(s=>s.status!=="approved"&&s.status!=="skipped"))throw new Error("所有阶段必须先 approved 或 skipped");const bad=this.db.prepare("SELECT COUNT(*) AS n FROM artifacts WHERE version_id=? AND state IN ('stale','rejected')").get(id);if(bad.n)throw new Error("存在 stale 或 rejected Artifact");this.db.prepare("UPDATE versions SET status='approved' WHERE id=? AND status='planning'").run(id);this.events?.append("version.approved",{versionId:id});return this.get(id);}
  seal(id){const v=this.get(id);if(v.status!=="approved")throw new Error("版本必须先 approved");if(v.release_path)throw new Error("版本已经发布，禁止重复 seal");const source=v.workspace_path;const finalRelease=join(this.root,"releases",new Date().toISOString().slice(0,10)+"-v"+v.version);if(existsSync(finalRelease))throw new Error("release 目录已存在，拒绝覆盖");const temp=finalRelease+".tmp-"+randomUUID();copyTree(source,temp);const artifacts=this.db.prepare("SELECT * FROM artifacts WHERE version_id=?").all(id);const approvals=this.db.prepare("SELECT * FROM approvals WHERE version_id=?").all(id);const files=filesOf(temp);const dependencies=this.db.prepare("SELECT d.* FROM artifact_dependencies d JOIN artifacts a ON a.id=d.artifact_id WHERE a.version_id=?").all(id);const manifest=buildManifest({version:v.version,versionId:id,baseVersionId:v.base_version_id,artifacts,approvals,tests:[],files,dependencies,createdAt:now()});const manifestPath=writeManifest(temp,manifest);writeFileSync(join(temp,"SEAL.ok"),JSON.stringify({versionId:id,manifest:manifestPath,createdAt:now()}));renameSync(temp,finalRelease);this.db.prepare("UPDATE versions SET status='released',release_path=? WHERE id=? AND status='approved'").run(finalRelease,id);this.events?.append("release.sealed",{versionId:id,release:finalRelease,manifestPath});return this.get(id);}
  forkVersion({baseVersionId,version}){const base=this.get(baseVersionId);const next=this.createVersion({projectId:base.project_id,version,baseVersionId});copyTree(base.workspace_path,next.workspace_path);const store=new StudioArtifactStore({db:this.db,eventLog:this.events});const artifacts=this.db.prepare("SELECT * FROM artifacts WHERE version_id=?").all(baseVersionId);for(const source of artifacts){if(["stale","rejected","deprecated","superseded"].includes(source.state))continue;store.inherit({versionId:next.id,sourceArtifactId:source.id,inheritMode:"reference"});}this.events?.append("version.forked",{baseVersionId,versionId:next.id,artifactCount:artifacts.length});return next;}
}
