import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { openStudioDb,closeStudioDb,StudioVersionStore,StudioArtifactStore,StudioBugStore } from "../src/studio/index.js";
test("Bug regression links use dedicated relation and same version",()=>{const root=mkdtempSync(join(tmpdir(),"studio-c025-"));const db=openStudioDb(join(root,".cowork","project.db"));const v=new StudioVersionStore({db,projectRoot:root});const p=v.createProject({name:"bugs"});const ver=v.createVersion({projectId:p.id,version:"0.1.6.0"});const arts=new StudioArtifactStore({db});const testArtifact=arts.create({versionId:ver.id,type:"test",name:"regression",state:"approved",checksum:"abc"});const bugs=new StudioBugStore({db});const bug=bugs.create({versionId:ver.id,title:"bad"});bugs.linkRegression({bugId:bug.id,testArtifactId:testArtifact.id});assert.equal(db.prepare("SELECT COUNT(*) AS n FROM bug_regression_tests").get().n,1);closeStudioDb(db);});
test("Artifact inherit rejects rejected source and keeps fork submitted",()=>{const root=mkdtempSync(join(tmpdir(),"studio-c025-art-"));const db=openStudioDb(join(root,".cowork","project.db"));const v=new StudioVersionStore({db,projectRoot:root});const p=v.createProject({name:"art"});const a=v.createVersion({projectId:p.id,version:"0.1.6.0"});const b=v.createVersion({projectId:p.id,version:"0.1.7.0"});const arts=new StudioArtifactStore({db});const source=arts.create({versionId:a.id,type:"doc",name:"x",state:"rejected",checksum:"abc"});assert.throws(()=>arts.inherit({versionId:b.id,sourceArtifactId:source.id}),/不可/);const good=arts.create({versionId:a.id,type:"doc",name:"y",state:"approved",checksum:"def"});const fork=arts.inherit({versionId:b.id,sourceArtifactId:good.id,inheritMode:"fork"});assert.equal(fork.state,"submitted");closeStudioDb(db);});
test("forkVersion registers source Artifact metadata",()=>{const root=mkdtempSync(join(tmpdir(),"studio-c025-fork-"));const db=openStudioDb(join(root,".cowork","project.db"));const v=new StudioVersionStore({db,projectRoot:root});const p=v.createProject({name:"fork"});const a=v.createVersion({projectId:p.id,version:"0.1.6.0"});const arts=new StudioArtifactStore({db});arts.create({versionId:a.id,type:"doc",name:"x",state:"approved",checksum:"abc"});const b=v.forkVersion({baseVersionId:a.id,version:"0.1.7.0"});assert.equal(db.prepare("SELECT COUNT(*) AS n FROM artifacts WHERE version_id=?").get(b.id).n,1);closeStudioDb(db);});
