import { mkdtempSync, writeFileSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { openStudioDb, closeStudioDb, StudioEventLog, StudioVersionStore, StageGateStore, StudioArtifactStore, StudioDocumentStore, StudioDocumentRunner } from "../src/studio/index.js";
import { createMockProvider } from "../src/providers/mock.js";

const root=mkdtempSync(join(tmpdir(),"studio-demo-"));
const db=openStudioDb(join(root,".cowork","project.db"));
const log=new StudioEventLog(join(root,".cowork","events.jsonl"));
const versions=new StudioVersionStore({db,eventLog:log,projectRoot:root});
const project=versions.createProject({name:"studio-demo"});
const v=versions.createVersion({projectId:project.id,version:"0.1.0.0"});
const gates=new StageGateStore({db,eventLog:log});
for(const stage of ["planning","design","asset-spec","production","playable"]){gates.start(v.id,stage);gates.transition(v.id,stage,"reviewing");gates.transition(v.id,stage,"approved");}
const artifacts=new StudioArtifactStore({db,eventLog:log});
const gdd=artifacts.create({versionId:v.id,type:"document",name:"main-design",state:"approved",checksum:"demo"});
const docs=new StudioDocumentStore({db,eventLog:log,workspacePath:v.workspace_path});
const runner=new StudioDocumentRunner({provider:createMockProvider({script:{default:()=>({summary:"demo design",content:"# System Design\n\nGenerated by Studio Agent.",done:true})}}),documentStore:docs,artifactStore:artifacts,eventLog:log});
const produced=await runner.run({agent:{id:"designer",role:"designer"},task:{id:"task-design",versionId:v.id,type:"document",name:"system-design"},inputs:[gdd],name:"system-design",format:"md"});
db.prepare("UPDATE artifacts SET state='approved' WHERE id=?").run(produced.id);
versions.approve(v.id);
const release=versions.seal(v.id);
const next=versions.forkVersion({baseVersionId:v.id,version:"0.1.1.0"});
const inherited=artifacts.inherit({versionId:next.id,sourceArtifactId:gdd.id,inheritMode:"reuse"});
console.log(JSON.stringify({root,release:release.release_path,next:next.version,inherited:inherited.inherit_mode,produced:produced.relativePath,events:readFileSync(join(root,".cowork","events.jsonl"),"utf8").trim().split("\n").length},null,2));
closeStudioDb(db);
